### ISSUE TITLE
Request to Join ModernApps Ninja Github Org

### ISSUE THREAD

**Issue by mallap** [ModernAppsNinja/modernappsninja.github.io#276]
#### By submitting this ticket, you acknowledge you have read and understood the registration instructions, and acknowledge and agree to the handling of the registration data you provide below as described in the registration instructions at the link above.
---

preferredEmailAddress: "Pradeep2405@gmail.com"  
firstName: "Pradeep"  
lastName: "Mallareddy"  
twitterUsername: "Pradeep Mallareddy"  
linkedinUsername: "Pradeep Kumar Mallareddy"  
isVmwareEmployee: false  
vmwareEmailAddress: "pmallareddy@vmware.com"

**Comment by afewell** [comment]
this workflow did not process because users github account needed verification before workflow can run. I reached out to user, they verified their github account and resubmitted their registration in a separate ticket which ran correctly. Closing this ticket.
