### ISSUE TITLE
Request to Join ModernApps Ninja Github Org

### ISSUE THREAD

**Issue by domedambrosio** [ModernAppsNinja/modernappsninja.github.io#661]
#### By submitting this ticket, you acknowledge you have read and understood the registration instructions, and acknowledge and agree to the handling of the registration data you provide below as described in the registration instructions at the link above.
---

preferredEmailAddress: "dome.dambrosio@gmail.com"  
firstName: "Domenico"  
lastName: "DAmbrosio"  
twitterUsername: ""  
linkedinUsername: "domenicodambrosio"  
isVmwareEmployee: false  
vmwareEmailAddress: ""

**Comment by afewell** [comment]
Hi @domedambrosio It looks like you found the issue, the script to process this initially had a problem processing the apostrophe in your last name, I see you updated the ticket and corrected the issue ... unfortunately right now the automated process only triggers when a new registration ticket is first created and it does not trigger when you edit a submitted ticket. 

If you could please re-submit a new registration issue ticket, the text in this ticket looks good now it just needs to be submitted as a new ticket to trigger the automation. You can enter the new ticket here [https://github.com/ModernAppsNinja/modernappsninja.github.io/issues/new?assignees=modernappsninjabot&labels=newuserregistration&template=joinrequest.md&title=Request+to+Join+ModernApps+Ninja+Github+Org](https://github.com/ModernAppsNinja/modernappsninja.github.io/issues/new?assignees=modernappsninjabot&labels=newuserregistration&template=joinrequest.md&title=Request+to+Join+ModernApps+Ninja+Github+Org)

Thank you!
