### ISSUE TITLE
Request to Join ModernApps Ninja Github Org

### ISSUE THREAD

**Issue by cpswan** [ModernAppsNinja/modernappsninja.github.io#78]
#### By submitting this ticket, you acknowledge you have read and understood the registration instructions, and acknowlege and agree to the handling of the registration data you provide below as described in the registration instructions at the link above.
---

preferredEmailAddress: "REMOVED"  
firstName: "Chris"  
lastName: "Swan"  
twitterUsername: "cpswan"  
linkedinUsername: "chrisswan"  
isVmwareEmployee: false  
vmwareEmailAddress: ""

**Comment by afewell** [comment]
Hi @cpswan normally this workflow runs immediately, but there appears to be some problem with the Github actions service right now as all workflows seem to be stuck in queue across all repositories. 

Sorry for the delay, I am hoping the service will be running again shortly and I will monitor the issue closely until its resolved. 

Ill post another message to you once I get it figured out. 

Thanks!

**Comment by afewell** [comment]
@cpswan I confirmed that Github is having a major outage for actions right now it seems to be impacting all of their users, so hopefully it will get fixed quickly thx

**Comment by afewell** [comment]
Hi @cpswan Github has recovered from their outage, but unfortunately workflows that were triggered during the outage window were killed. Would you mind resubmitting a new registration ticket? Sorry for the inconvenience, the automated workflow should have you all setup within a few minutes of registering. I will keep an eye out for your registration and if for any reason it fails again I will set you up manually. Thanks so much!

**Comment by cpswan** [comment]
OK. Will do. @afewell I'm guessing that part of the Action is to delete the issue (so that emails aren't left sat around), so can you please do that for this one.
