### ISSUE TITLE
Link from learnmore menu is broken

### ISSUE THREAD

**Issue by pescerosso** [ModernAppsNinja/modernappsninja.github.io#939]
**Describe the bug**
Link from learnmore menu is broken

https://github.com/ModernAppsNinja/modernappsninja.github.io/discussions

**To Reproduce**
clink on learnmore
then ask us anything

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by afewell** [comment]
fixed, thanks @pescerosso !!!
